# fly.toml app configuration file generated for iracing-bot on 2025-05-27T10:50:33+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iracing-bot'
primary_region = 'syd'

[build]

[[mounts]]
source = 'iracing_bot_data'
destination = '/data'

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
