# fly.toml app configuration file generated for iracing-bot on 2025-05-27T10:50:33+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iracing-bot'
primary_region = 'syd'

[build]

[[mounts]]
  source = 'iracing_bot_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
